config/routes.rb
Rails.application.routes.draw do
  get 'summaries/index'

  root 'static_pages#home'
  get 'wedding_party' => 'static_pages#wedding_party'
  get 'event' => 'static_pages#event'
  get 'travel' => 'static_pages#travel'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources:foodstuffs, :except => [:show, :destroy]
  resources:guests, :except => :show

  resources:rsvps, :only => [:edit, :update] do
    collection do
      get 'find'
      post 'locate'
    end
  end

  resources:summaries, :only => [:index]
  resources:users, :except => [:show, :destroy]
end

app/models/foodstuff.rb
class Foodstuff < ActiveRecord::Base
  validates(:foodstuff_name, presence: true, length: { maximum: 50 })
  validates(:foodstuff_description, length: { maximum: 250 })

  has_many :guests
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  validates(:full_name, presence: true, length: { maximum: 50 })
  validates(:foodstuff_id, :presence => true, :if => "attending_ind?")
  belongs_to :foodstuff

  before_save :update_attending_ind!
  private
  def update_attending_ind!
    if !self.attending_ind
      self.foodstuff_id = nil
      self.additional_comment = nil
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true, length: { maximum: 255 },  format: { with: VALID_EMAIL_REGEX },  uniqueness: true)
  validates(:first_name, presence: true, length: { maximum: 50 })
  validates(:last_name, presence: true, length: { maximum: 50 })
  has_secure_password()
  validates(:password, presence:true, length: { minimum: 6 })

  before_save { self.email = email.downcase }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/foodstuffs_controller.rb
class FoodstuffsController < ApplicationController
  before_action :logged_in_user
  def index
    @foodstuffs = Foodstuff.all.order('foodstuff_name ASC')
  end

  def new
    @foodstuff = Foodstuff.new
  end

  def create
    @foodstuff = Foodstuff.new(user_params)
    if @foodstuff.save
      flash[:success] = "Foodstuff succesfully added."
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def edit
    @foodstuff = Foodstuff.find(params[:id])
  end

  def update
    @foodstuff = Foodstuff.find(params[:id])
    if @foodstuff.update_attributes(user_params)
      flash[:success] = "Foodstuff updated."
      redirect_to action: :index
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:foodstuff)
    .permit(:foodstuff_name, :foodstuff_description)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :logged_in_user

  def index
    @guests = Guest.includes(:foodstuff).all.order('full_name ASC')
  end

  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(user_params)
    if @guest.save
      flash[:success] = "Guest successfully created."
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def update
    @guest = Guest.find(params[:id])
    if @guest.update_attributes(user_params)
      flash[:success] = "Guest successfully updated."
      redirect_to action: :index
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:guest)
    .permit(:full_name, :foodstuff_id, :additional_comment, :attending_ind)
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

  def find
    render 'find'
  end

  def locate
    if params[:rsvp_name_query].blank? || params[:rsvp_name_query].length < 4
      flash.now[:warning] = "Veuillez entrer un nom"
      return render 'find'
    end

    @guests = Guest.where("unaccent(lower(full_name)) LIKE ?", "%#{I18n.transliterate(params[:rsvp_name_query].downcase)}%")
    if @guests.length > 0
      redirect_to action: :edit, id: @guests[0].id
    else
      flash.now[:danger] = "Aucun RSVP n'a été trouvé pour ce nom; veuillez vérifier votre saisie et réessayer."
      render 'find'
    end
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def update
    @guest = Guest.find(params[:id])

    if @guest.update_attributes(user_params)
      flash[:success] = "Votre RSVP a été mis à jour. Merci"
      redirect_to action: :find
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:guest)
    .permit(:foodstuff_id, :additional_comment, :attending_ind)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user.id
      redirect_back_or root_url
    else
      flash.now[:danger] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
  end

  def event
  end

  def wedding_party
  end

  def travel
  end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  before_action :logged_in_user

  def index
    @guests = Guest.includes(:foodstuff).all.order('full_name ASC')
    @foodstuffs = Foodstuff.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User successfully created."
      redirect_to action: :index
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Information sauvegarder"
      redirect_to(action: :edit)
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodstuff_helper.rb
module FoodstuffHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user_id)
    session[:user_id] = user_id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foodstuffs/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
    <h1>Midification de repas</h1>

    <%= form_for(@foodstuff) do |f| %>
    <%= render 'shared/error_messages', obj: @foodstuff %>

    <div class="form-group">
      <%= f.label :foodstuff_name, "Repas" %>
      <%= f.text_field :foodstuff_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :foodstuff_description, "Description (optionnel)" %>
      <%= f.text_area :foodstuff_description, class: 'form-control' %>
    </div>
    <%= f.submit "Sauvegarder", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/foodstuffs/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="panel panel-default">
      <div class="panel-heading">Repas</div>
      <table class="table table-condensed table-striped">
        <thead>
          <th>Repas</th>
          <th>Description</th>
        </thead>
        <tbody>
          <% @foodstuffs.each do |foodstuff| %>
          <tr>
            <td><%= link_to foodstuff.foodstuff_name, edit_foodstuff_path(foodstuff) %></td>
            <td><%= foodstuff.foodstuff_description %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="panel-footer">
        <%= link_to "Nouveau repas", new_foodstuff_path, class: "btn btn-primary" %>
      </div>
    </div>
    
  </div>
</div>

app/views/foodstuffs/new.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
    <h1>Nouveau Repas</h1>

    <%= form_for(@foodstuff) do |f| %>
    <%= render 'shared/error_messages', obj: @foodstuff %>

    <div class="form-group">
      <%= f.label :foodstuff_name, "Repas" %>
      <%= f.text_field :foodstuff_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :foodstuff_description, "Description (optionnel)" %>
      <%= f.text_area :foodstuff_description, class: 'form-control' %>
    </div>
    <%= f.submit "Sauvegarder", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/guests/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
    <h1>Modification d'un invité</h1>

    <%= form_for(@guest) do |f| %>
    <%= render 'shared/error_messages', obj: @guest %>

    <div class="form-group">
      <%= f.label :full_name, "Nom complet" %>
      <%= f.text_field :full_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :foodstuff, "Choix de repas" %><br />
      <%= f.select :foodstuff_id, Foodstuff.all.collect {|foodstuff| [ foodstuff.foodstuff_name, foodstuff.id ]}, {}, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :additional_comment, "Information additionnelle (par exemple: Allergies)" %>
      <%= f.text_area :additional_comment, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attending_ind, "Présence confirmé?" %>
      <%= f.select :attending_ind, [['Oui', true], ['Non', false]], {}, class: 'form-control'%>
    </div>
    <%= f.submit "Sauvegarder", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/guests/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="panel panel-default">
      <div class="panel-heading">Invités</div>

      <table class="table table-condensed table-striped">
        <thead>
          <th>Nom d'invité</th>
          <th>Repas</th>
          <th>Information Additionnelle</th>
          <th>Présence confirmé</th>
        </thead>
        <tbody>
          <% @guests.each do |guest| %>
          <tr>
            <td><%= link_to "#{guest.full_name}", edit_guest_path(guest) %></td>
            <td><%= guest.foodstuff.foodstuff_name if guest.foodstuff_id? %></td>
            <td><%= check_box_tag "guest_ids[]", guest.id, !guest.additional_comment.blank?, {:id => "guest_id_#{guest.id}", :class => "checkbox", :disabled => ""} %></td>
            <td><%= check_box_tag "guest_ids[]", guest.id, guest.attending_ind?, {:id => "guest_id_#{guest.id}", :class => "checkbox", :disabled => ""} %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="panel-footer">
        <%= link_to "Nouvel Invité", new_guest_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/guests/new.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
    <h1>Nouvelle Invité</h1>

    <%= form_for(@guest) do |f| %>
    <%= render 'shared/error_messages', obj: @guest %>

    <div class="form-group">
      <%= f.label :full_name, "Nom complet" %>
      <%= f.text_field :full_name, class: 'form-control' %>
    </div>
    <%= f.submit "Sauvegarder", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/layouts/_wedded_people_header.html.erb
<!-- <div class="container-fluid container-table"> -->
<div class="row vertical-center-row">
  <div class="col-sm-8 col-sm-offset-2 home-title-area">
    <a href="<%= root_path %>">
      <h1 class="site-title text-center"  style="letter-spacing: 0.15em;">
        Cassandre &amp; Marie-Michèle
        <p class="site-tagline text-center" data-shrink-original-size="20" style="letter-spacing: 0.15em;">SE MARIENT</p>
      </h1>
    </a>
  </div>
</div>
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% provide(:title, "Cass & Marie") %>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
  'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :head %>
  <%= csrf_meta_tags %>

  <!-- Lato font -->
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:100,400,300,300italic,700normal,700italic,700,400italic">
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand visible-xs" href="#">Menu</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <li><%= link_to "Cortège", wedding_party_path %></li>
          <li><%= link_to "Événement", event_path %></li>
          <li><%= link_to "Hébergement", travel_path %></li>
          <li><%= link_to "RSVP", find_rsvps_path %></li>

          <% if logged_in?  %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gestion <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Invités", guests_path %></li>
              <li><%= link_to "Repas", foodstuffs_path %></li>
              <li><%= link_to "Sommaires", summaries_path %></li>
              <li><%= link_to "Usagés", users_path %></li>
            </ul>
          </li>
          <% end %>
        </ul>

        <% if logged_in?  %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Log-Out", logout_path, method: :delete%></li>
        </ul>
        <p class="navbar-text navbar-right text-primary">
          <small>Connecté en tant que: <%= link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_path(current_user) %></small>
        </p>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Log-In", login_path %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= message %></div>
      <% end %>
      <%= yield %>
    </div>

    <% if Rails.env.development? %>
    <div class="container" style="margin-top:-90px">
      <div class='row'>
        <div class='col-lg-12'>
          <%= debug(params) %>
        </div>
      </div>
    </div>
    <% end %>
  </body>

  <footer class="footer">

  </footer>
  </html>

app/views/rsvps/edit.html.erb
<% content_for :head do %>
<script type="text/javascript">
$(document).ready(function(){
  toggleEnabled();
  $('#cboAttendingInd').change(function(){
    toggleEnabled();
  });

  function toggleEnabled(){
    if ($( "#cboAttendingInd option:selected" ).val() == 'true'){
      $('#cboFoodstuff').removeAttr('disabled');
      $('#txtAdditionalComment').removeAttr('disabled');
    }else{
      $('#cboFoodstuff').attr('disabled', '').val('');
      $('#txtAdditionalComment').attr('disabled', '').text('');
    }
  }
});
</script>
<% end %>

<%= render 'layouts/wedded_people_header' %>
<div class="row vertical-center-row">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 home-title-area">
    <p class="site-tagline text-center"> RSVP pour <%= "#{@guest.full_name}"%></p>
    <small class="text-center text-muted"><%= link_to "(Ceci n'est pas votre invitation? Cliquez ici pour faire une nouvelle recherche)", find_rsvps_path %></small>

    <%= form_for(@guest, :url => rsvp_path(@guest)) do |f| %>
    <%= render 'shared/error_messages', obj: @guest, include_desc: false %>

    <div class="form-group">
      <%= f.label :attending_ind, "Allez-vous assister à l'événement?" %>
      <%= f.select :attending_ind, [['Oui', true], ['Non', false]], {}, id: "cboAttendingInd", class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :foodstuff, "Choix de repas" %><br />
      <%= f.select :foodstuff_id, Foodstuff.all.collect {|foodstuff| [ foodstuff.foodstuff_name, foodstuff.id ]}, { :include_blank => true }, id: "cboFoodstuff", class: "form-control", disabled: "" %>
    </div>
    <div class="form-group">
      <%= f.label :additional_comment, "Information additionnelle (par exemple: Allergies)" %>
      <%= f.text_area :additional_comment, id: "txtAdditionalComment", class: 'form-control', disabled: "" %>
    </div>

    <%= f.submit "Soumettre RSVP", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/rsvps/find.html.erb
<%= render 'layouts/wedded_people_header' %>

<script type="text/javascript">
$(document).ready(function(){
  $('#txtRSVPTxt').popover();
});
</script>

<div class="row vertical-center-row">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 home-title-area">

    <p class="site-tagline text-cente">Entrez le nom sur votre invitation</p>

    <%= form_tag locate_rsvps_path do %>
    <div class="input-group">
      <%= text_field_tag "rsvp_name_query", nil, class:"form-control input", placeholder: "Par exemple: Jane Doe", required: true %>
      <span class="input-group-btn">
        <button type="submit" class="btn btn-default">Trouver RSVP</button>
      </span>
    </div>
    <% end %>

    <% helpContent = 'Chaque personne dont le nom est inscrit sur l\'invitation doit remplir et soumettre individuellement un RSVP.'%>
    <small class="text-right">
      <u id="txtRSVPTxt" data-toggle="popover" data-trigger="hover" data-placement="bottom" data-content="<%= helpContent %>">Information additionnelle</u>
    </small>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
<div id="error_summary">
  <div class="alert alert-danger">
    La page contient <%= pluralize(obj.errors.count, "erreur") %>.
  </div>

  <% if !defined?(include_desc) || include_desc %>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
</div>
<% end %>

app/views/static_pages/_party_member.html.erb
<%class_txt = "info-border-top" if include_border_top%>
<div class="row <%= raw class_txt %>">
  <% if even %>
  <div class="col-xs-4">
    <a href="#" class="thumbnail">
      <img src="<%= pic_url %>" alt="">
    </a>
  </div>
  <div class="col-xs-8 text-right">
    <div class="info">
      <h2>
        <%= raw name %> <br>
        <small><%= raw title %></small>
      </h2>
    </div>
  </div>
  <% else %>
  <div class="col-xs-8">
    <div class="info">
      <h2>
        <%= raw name %> <br>
        <small><%= raw title %></small>
      </h2>
    </div>
  </div>
  <div class="col-xs-4">
    <a href="#" class="thumbnail">
      <img src="<%= pic_url %>" alt="">
    </a>
  </div>
  <% end %>
</div>

app/views/static_pages/event.html.erb
<%= render 'layouts/wedded_people_header' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="bs-panel">

      <div class="row">
        <div class="col-md-7">
          <h3>Où?</h3>
          <address>
            Espace du 400e<br />
            100 Quai St-André<br />
            Québec, QC, G1K 3Y2
          </address>
          <p>
            <a class="btn btn-default" href="https://maps.google.com/maps?saddr=Current+Location&amp;daddr=100 Quai St-André, Québec, Qc G1K 3Y2" target="_blank">Directions</a>
          </p>

          <div class="row info-border-top">
            <div class="col-md-12">
              <h3>Événements
              </h3>
              <div class="info" style="padding-top:10px;">
                <div>
                  <h4>
                    Cérémonie du mariage<br />
                    <small>Samedi 20 février 2016<br />17h00</small>
                  </h4>
                </div>
              </div>
              <div class="info">
                <div>
                  <h4>
                    Cocktail<br />
                    <small>Patrice Plante sera notre mixologue invité! (Restaurant L'Atelier Tartares et Cocktails, auteur du livre <i>L'Atelier: L'Art du cocktail</i>, animateur à l'émission <i>Le Bon Mix selon Boire</i>, chroniqueur cocktails à <i>Salut, Bonjour</i>!)</small>
                  </h4>
                </div>
              </div>
              <div class="info">
                <div>
                  <h4>
                    Réception du mariage<br />
                    <small>Souper 4 services et DJ</small>
                  </h4>
                </div>
              </div>
            </div>
          </div>

        </div>
        <div class="col-md-5">
          <div class="flexible-container">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2730.3387893775466!2d-71.20764228400624!3d46.817329279140274!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cb895e0cee1094f%3A0x9065362c2a42f87b!2sEspace+400e+Bell%2C+100+Quai+Saint-Andr%C3%A9%2C+Qu%C3%A9bec%2C+QC+G1K+3Y2!5e0!3m2!1sen!2sca!4v1446786189998" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container-table container-fluid">
  <div class="row vertical-center-row">
    <div class="col-sm-8 col-sm-offset-2 home-title-area">
      <a href="<%= root_path %>">
        <h1 class="site-title text-center"  style="letter-spacing: 0.15em;">
          Cassandre &amp; Marie-Michèle
          <p class="site-tagline text-center" data-shrink-original-size="20" style="letter-spacing: 0.15em;">SE MARIENT</p>
        </h1>
      </a>
    </div>
  </div>
</div>

app/views/summaries/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="panel panel-default">
      <div class="panel-heading">Sommaire</div>

      <table class="table table-condensed table-bordered">
        <tbody>
          <!--  Group -->
          <tr class="table-row-alternate">
            <td colspan="2"><b>General:</b></td>
          </tr>

          <tr>
            <td>Invités confirmer</td>
            <td><%= @guests.where(:attending_ind => true).count %>/<%= @guests.count %></td>
          </tr>

          <tr>
            <td>Invités confirmés avec de l'information additionnelle</td>
            <td><%= @guests.where(:attending_ind => true).where.not(:additional_comment => "").count %></td>
          </tr>
          <!--  Group -->
          <tr class="table-row-alternate">
            <td colspan="2"><b>Repas:</b></td>
          </tr>
          <% @foodstuffs.each do |foodstuff| %>
          <tr>
            <td><%= foodstuff.foodstuff_name %></td>
            <td><%= @guests.where(:foodstuff_id => foodstuff.id).count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="panel panel-default">
      <div class="panel-heading">Usagés</div>

      <table class="table table-condensed table-striped">
        <thead>
          <th>Email</th>
          <th>Nom</th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= "#{user.first_name} #{user.last_name}" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="panel-footer">
        <%= link_to "Nouvel Usagé", new_user_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>